# Which collections CloudCannon will show in the CMS sidebar
collections_config:
  SAFI:
    name: SAFI
    path: "docs/SAFI"
    output: true
    url: "/[full_slug]/" # mkdocs' default url behavior for nested files
  MemoJavaScript:
    name: MÃ©mo Javascript
    path: "docs/memo-javascript"
    output: true
    url: "/[full_slug]/" # mkdocs' default url behavior for nested files


# The available buttons in the CloudCannon Content Editor
_editables:
  content:
    link: true
    blockquote: true
    bold: true
    format: "p h1 h2 h3 h4 h5 h6"
    italic: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    bulletedlist: true
    indent: true
    numberedlist: true
    outdent: true
    code: true
    embed: true
    horizontalrule: true
    image: true
    table: true
    undo: true
    redo: true
    removeformat: true
    copyformatting: true